services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: norasil-images
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:secret@db:5432/images?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: norasil-images-db
    environment:
      - POSTGRES_DB=images
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
